version: '3.3'

volumes:
  traefik-public-certificates:

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: 'uvicorn app.main:app --host 0.0.0.0'
    expose:
      - 8000

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.django.rule=Host(`guysportfolio.com`)"
      - "traefik.http.routers.django.tls=true"
      - "traefik.http.routers.django.tls.certresolver=letsencrypt"

  traefik:
    build:
      context: .
      dockerfile: Dockerfile.traefik
    ports:
      - 80:80
      - 443:443
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik-public-certificates:/certificates"